### ISSUE TITLE
Got a question regarding the certs

### ISSUE THREAD

**Issue by gbdavidx** [JPHutchins/pgesmd_self_access#3]
How do i know what exactly my private key is? I create a site using godaddy and they basically have everything automated using their internal pki system, but i have three files:
12e926f0d436f640.crt
12e926f0d436f640.pem
sfig2_bundle.crt - this has what appears to be both private and public
what is   "cert_key_path" : string, like above?

Ive been struggling with this for weeks, and i think i might have some end in site.  I know a little about security since im studying for sans 401 - but i have never used an ssl for post requests before, any help would be greatly appreciated!

**Comment by gbdavidx** [comment]
pip install pgesmd_self_access
isnt this for python2?

i get an error when i try to test
from pgesmd_self_access.api import SelfAccessApi
pge_api = SelfAccessApi.auth( < full path to the auth.json > ) # for example, /home/jp/pgesmd_self_access/auth/auth.json
pge_api.get_service_status()

No module named 'pgesmd_self_access.api?

**Comment by gbdavidx** [comment]
<img width="1021" alt="Screen Shot 2021-12-08 at 10 05 51 AM" src="https://user-images.githubusercontent.com/26369204/145260465-12ae0cb4-4266-4451-8ba1-c10fa79cb529.png">
So im not sure why im doing wrong, but i copied everything over and create the auth.json (with keys and secret code/password), but im getting an invalid syntax

**Comment by gbdavidx** [comment]
i also ttief with python3 and got the same error, please help!

**Comment by gbdavidx** [comment]
https://imgur.com/a/5X1uv52 please help! i found my certs, but cant reference my cert location now :(

**Comment by gbdavidx** [comment]
if i run it as sudo python3, i dont get an error but get access denied, any ideas why i could get denied? I sent them my public key 
<img width="1064" alt="Screen Shot 2021-12-08 at 12 04 25 PM" src="https://user-images.githubusercontent.com/26369204/145276476-a3a3e8e9-edfd-46fd-af56-e2aee2b06c32.png">

**Comment by JPHutchins** [comment]
I see that this is done on a homeassistant machine.  I don't know what user and permissions are like so I'd recommend setting this up again on local/vm "regular" linux or windows machine.  There shouldn't be any permission errors caused by copying the text of your public and private certs to the certs folder and then defining those paths in the auth.json.

Also, what do you mean by "I sent them my public key" - do you mean at the PG&E share my data portal?  If so, e-mail them to ask if you are ready to test.  You could also post the status messages from the portal with the keys redacted.

Finally, it's possible that they have changed their APIs and this repo needs to be updated!
